// Mock data for when database is not connected
export const MOCK_VEHICLES = [
  {
    id: '1',
    slug: 'lamborghini-huracan-yellow',
    displayName: 'Lamborghini Huracán',
    make: 'Lamborghini',
    model: 'Huracán',
    year: 2023,
    category: 'SPORT',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 2,
    doors: 2,
    engineSize: 5.2,
    engineType: 'V10',
    horsePower: 631,
    torque: 600,
    topSpeed: 325,
    acceleration: 2.9,
    fuelConsumption: 14.9,
    features: ['All-Wheel Drive', 'Carbon Ceramic Brakes', 'Alcantara Interior', 'Performance Data Recorder', 'Lamborghini Dynamic Steering'],
    primaryImageUrl: '/Lamborghini-Huracan-Yellow.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 999,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 150,
      extraKmPrice: 8,
      depositAmount: 10000,
      isActive: true
    }],
    featured: true,
    featuredOrder: 1,
    licensePlate: 'FLY-001',
    vin: 'ZHW1234567890',
    trim: 'EVO',
    description: 'Experience the raw power and Italian craftsmanship of the iconic Lamborghini Huracán.',
    _count: { bookings: 0 }
  },
  {
    id: '2',
    slug: 'lamborghini-urus-green',
    displayName: 'Lamborghini Urus',
    make: 'Lamborghini',
    model: 'Urus',
    year: 2023,
    category: 'LUXURY',
    bodyType: 'SUV',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 4.0,
    engineType: 'Twin-Turbo V8',
    horsePower: 641,
    torque: 850,
    topSpeed: 305,
    acceleration: 3.6,
    fuelConsumption: 12.7,
    features: ['Active Roll Stabilization', 'Carbon Ceramic Brakes', 'Adaptive Air Suspension', 'Premium Bang & Olufsen Sound', 'Lamborghini Infotainment System'],
    primaryImageUrl: '/Lamborghini-Urus-Green.png',
    images: [],
    priceRules: [{
      basePricePerDay: 1199,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 8,
      depositAmount: 12000,
      isActive: true
    }],
    featured: true,
    featuredOrder: 2,
    licensePlate: 'FLY-002',
    vin: 'ZHW0987654321',
    trim: 'S',
    description: 'The world\'s first Super Sport Utility Vehicle - luxury meets extreme performance.',
    _count: { bookings: 0 }
  },
  {
    id: '3',
    slug: 'mercedes-amg-sl63',
    displayName: 'Mercedes-AMG SL63',
    make: 'Mercedes-Benz',
    model: 'AMG SL63',
    year: 2023,
    category: 'LUXURY',
    bodyType: 'CONVERTIBLE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 2,
    doors: 2,
    engineSize: 4.0,
    engineType: 'Twin-Turbo V8',
    horsePower: 577,
    torque: 800,
    topSpeed: 315,
    acceleration: 3.5,
    fuelConsumption: 11.8,
    features: ['4MATIC+ All-Wheel Drive', 'AMG Active Ride Control', 'Burmester 3D Surround Sound', 'AMG Performance Steering Wheel', 'Airscarf Neck-Level Heating'],
    primaryImageUrl: '/Mercedes-AMG-SL63.png',
    images: [],
    priceRules: [{
      basePricePerDay: 899,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 7,
      depositAmount: 9000,
      isActive: true
    }],
    featured: true,
    featuredOrder: 3,
    licensePlate: 'FLY-003',
    vin: 'WDC1234567890',
    trim: 'AMG',
    description: 'Elegance and performance united in the legendary Mercedes-AMG SL63 roadster.',
    _count: { bookings: 0 }
  },
  {
    id: '4',
    slug: 'porsche-911-gt3-rs',
    displayName: 'Porsche 911 GT3 RS',
    make: 'Porsche',
    model: '911 GT3 RS',
    year: 2023,
    category: 'SPORT',
    bodyType: 'COUPE',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'RWD',
    seats: 2,
    doors: 2,
    engineSize: 4.0,
    engineType: 'Flat-6',
    horsePower: 518,
    torque: 465,
    topSpeed: 296,
    acceleration: 3.2,
    fuelConsumption: 12.4,
    features: ['Rear-Wheel Drive', 'Carbon Ceramic Brakes', 'Active Aerodynamics', 'GT Sport Steering Wheel', 'Track Precision App'],
    primaryImageUrl: '/Porsche-GT3RS-Grey-Black.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 949,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 150,
      extraKmPrice: 7,
      depositAmount: 9500,
      isActive: true
    }],
    featured: true,
    featuredOrder: 4,
    licensePlate: 'FLY-004',
    vin: 'WPO1234567890',
    trim: 'GT3 RS',
    description: 'The ultimate track-focused street-legal Porsche - precision engineering meets motorsport heritage.',
    _count: { bookings: 0 }
  }
]

export const MOCK_BOOKINGS = []
export const MOCK_USERS = []
export const MOCK_ADDONS = []
