// Mock data for when database is not connected
export const MOCK_VEHICLES = [
  {
    id: '1',
    slug: 'audi-s5-sportback',
    displayName: 'Audi S5 Sportback',
    make: 'Audi',
    model: 'S5',
    year: 2020,
    category: 'SPORT',
    bodyType: 'SEDAN',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 3.0,
    engineType: 'Turbo V6',
    horsePower: 349,
    torque: 369,
    topSpeed: 250,
    acceleration: 4.7,
    fuelConsumption: 8.3,
    features: ['quattro All-Wheel Drive', 'Virtual Cockpit', 'MMI Navigation Plus', 'Bang & Olufsen Sound System', 'Audi Drive Select'],
    primaryImageUrl: '/AudiS5-1.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 220,
      weekendMultiplier: 1.15,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 5,
      depositAmount: 2200,
      isActive: true
    }],
    featured: true,
    featuredOrder: 1,
    licensePlate: 'FLY-001',
    vin: 'WAU1234567890',
    trim: 'Sportback',
    description: 'Experience the pinnacle of automotive excellence with the Audi S5 Sportback.',
    _count: { bookings: 0 }
  },
  {
    id: '2',
    slug: 'audi-s3-sedan',
    displayName: 'Audi S3 Sedan',
    make: 'Audi',
    model: 'S3',
    year: 2019,
    category: 'SPORT',
    bodyType: 'SEDAN',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 2.0,
    engineType: 'Turbo I4',
    horsePower: 288,
    torque: 280,
    topSpeed: 250,
    acceleration: 4.8,
    fuelConsumption: 7.4,
    features: ['quattro All-Wheel Drive', 'Virtual Cockpit', 'MMI Navigation', 'Audi Sound System', 'Audi Drive Select'],
    primaryImageUrl: '/AudiS3-1.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 200,
      weekendMultiplier: 1.15,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 5,
      depositAmount: 2000,
      isActive: true
    }],
    featured: true,
    featuredOrder: 2,
    licensePlate: 'FLY-002',
    vin: 'WAU0987654321',
    trim: 'Sedan',
    description: 'Compact luxury sedan with exceptional performance and quattro all-wheel drive.',
    _count: { bookings: 0 }
  }
]

export const MOCK_BOOKINGS = []
export const MOCK_USERS = []
export const MOCK_ADDONS = []
