// Mock data for when database is not connected
export const MOCK_VEHICLES = [
  {
    id: '1',
    slug: 'mercedes-amg-c43',
    displayName: 'Mercedes-AMG C43',
    make: 'Mercedes-Benz',
    model: 'C43 AMG',
    year: 2024,
    category: 'LUXURY',
    bodyType: 'SEDAN',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 3.0,
    engineType: 'V6 Biturbo',
    horsePower: 385,
    torque: 520,
    topSpeed: 250,
    acceleration: 4.7,
    fuelConsumption: 8.5,
    features: ['Bluetooth', 'GPS Navigation', 'Leather Seats', 'Heated Seats', 'Apple CarPlay'],
    primaryImageUrl: '/C43Silver-1.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 450,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 0.5,
      depositAmount: 1000,
      isActive: true
    }],
    featured: true,
    featuredOrder: 1,
    licensePlate: 'FLY-001',
    vin: 'WDD1234567890',
    trim: 'AMG Line',
    description: 'Experience luxury and performance with our Mercedes-AMG C43.',
    _count: { bookings: 0 }
  },
  {
    id: '2',
    slug: 'porsche-cayenne',
    displayName: 'Porsche Cayenne',
    make: 'Porsche',
    model: 'Cayenne',
    year: 2024,
    category: 'SUV',
    bodyType: 'SUV',
    status: 'ACTIVE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    engineSize: 3.0,
    engineType: 'V6 Turbo',
    horsePower: 335,
    torque: 450,
    topSpeed: 230,
    acceleration: 6.2,
    fuelConsumption: 9.2,
    features: ['Bluetooth', 'GPS Navigation', 'Leather Seats', 'Sunroof', 'Apple CarPlay'],
    primaryImageUrl: '/PorscheCayenneWhite-1.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 550,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 0.5,
      depositAmount: 1200,
      isActive: true
    }],
    featured: true,
    featuredOrder: 2,
    licensePlate: 'FLY-002',
    vin: 'WP1234567890',
    trim: 'Base',
    description: 'Luxury SUV with exceptional performance and comfort.',
    _count: { bookings: 0 }
  },
  {
    id: '3',
    slug: 'mercedes-cla-250',
    displayName: 'Mercedes CLA 250',
    make: 'Mercedes-Benz',
    model: 'CLA 250',
    year: 2018,
    category: 'LUXURY',
    bodyType: 'SEDAN',
    status: 'MAINTENANCE',
    transmission: 'AUTOMATIC',
    fuelType: 'PETROL',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    engineSize: 2.0,
    engineType: 'I4 Turbo',
    horsePower: 221,
    torque: 350,
    topSpeed: 210,
    acceleration: 6.8,
    fuelConsumption: 7.1,
    features: ['Bluetooth', 'GPS Navigation', 'Backup Camera', 'USB Charging'],
    primaryImageUrl: '/2018-CLA250.jpg',
    images: [],
    priceRules: [{
      basePricePerDay: 350,
      weekendMultiplier: 1.2,
      weeklyDiscount: 10,
      monthlyDiscount: 20,
      minimumDays: 1,
      maximumDays: 30,
      includedKmPerDay: 200,
      extraKmPrice: 0.5,
      depositAmount: 800,
      isActive: true
    }],
    featured: false,
    featuredOrder: 0,
    licensePlate: 'FLY-003',
    vin: 'WDD0987654321',
    trim: 'Sport',
    description: 'Stylish and efficient luxury sedan for everyday elegance.',
    _count: { bookings: 0 }
  }
]

export const MOCK_BOOKINGS = []
export const MOCK_USERS = []
export const MOCK_ADDONS = []
